services:
  database:
    container_name: "postgres-dev"
    image: postgres:16.15-alpine
    env_file:
      - ./.env
    # Adicione esta seção para traduzir as variáveis para o Postgres
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - "5432:5432"