ALTER TABLE "users"
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "sessions"
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "monitor_targets"
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
